import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const variablesDir = path.join(root, "public", "variables");
const outFile = path.join(root, "src", "styles", "generated-tokens.css");

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function isTokenObject(v) {
  return v && typeof v === "object" && ("$value" in v || "$type" in v);
}

function collectLeafTokens(obj, prefix = []) {
  /** @type {Array<{name: string, token: any}>} */
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k === "$extensions") continue;
    if (isTokenObject(v) && "$value" in v) {
      out.push({ name: [...prefix, k].join("-"), token: v });
      continue;
    }
    if (v && typeof v === "object") out.push(...collectLeafTokens(v, [...prefix, k]));
  }
  return out;
}

function cssEscapeVarName(name) {
  // Keep it conservative: lowercase, replace non-alphanum with '-'
  return name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/--+/g, "-");
}

function toCssValue(token) {
  const v = token?.$value;
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return v;
  if (v && typeof v === "object" && typeof v.hex === "string") return v.hex;
  return null;
}

function renderBlock(selector, tokens, { prefix = "gs" } = {}) {
  const lines = [];
  lines.push(`${selector} {`);
  for (const { name, token } of tokens) {
    const cssValue = toCssValue(token);
    if (!cssValue) continue;
    const varName = `--${prefix}-${cssEscapeVarName(name)}`;
    lines.push(`  ${varName}: ${cssValue};`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function main() {
  const lightPath = path.join(variablesDir, "mode", "light mode.tokens.json");
  const darkPath = path.join(variablesDir, "mode", "dark mode.tokens.json");
  const tokensPath = path.join(variablesDir, "tokens", "Mode 1.tokens.json");
  const twFontPath = path.join(variablesDir, "tw_font", "Mode 1.tokens.json");
  const twColorsPath = path.join(variablesDir, "tw_colors", "Mode 1.tokens.json");
  const twGapPath = path.join(variablesDir, "tw_gap", "Mode 1.tokens.json");
  const twSpacePath = path.join(variablesDir, "tw_space", "Mode 1.tokens.json");
  const twPaddingPath = path.join(variablesDir, "tw_padding", "Mode 1.tokens.json");
  const twMarginPath = path.join(variablesDir, "tw_margin", "Mode 1.tokens.json");

  if (!fs.existsSync(lightPath) || !fs.existsSync(darkPath)) {
    console.error("Missing mode token files under public/variables/mode/.");
    console.error(`Expected: ${lightPath}`);
    console.error(`Expected: ${darkPath}`);
    process.exitCode = 2;
    return;
  }

  const light = readJson(lightPath);
  const dark = readJson(darkPath);

  const lightTokens = collectLeafTokens(light);
  const darkTokens = collectLeafTokens(dark);

  // Foundations (numbers + typography) are not mode-specific in this export.
  const numberTokens = fs.existsSync(tokensPath)
    ? collectLeafTokens(readJson(tokensPath))
    : [];
  const twFontTokens = fs.existsSync(twFontPath)
    ? collectLeafTokens(readJson(twFontPath))
    : [];
  const twColorTokens = fs.existsSync(twColorsPath)
    ? collectLeafTokens(readJson(twColorsPath))
    : [];
  const twGapTokens = fs.existsSync(twGapPath)
    ? collectLeafTokens(readJson(twGapPath))
    : [];
  const twSpaceTokens = fs.existsSync(twSpacePath)
    ? collectLeafTokens(readJson(twSpacePath))
    : [];
  const twPaddingTokens = fs.existsSync(twPaddingPath)
    ? collectLeafTokens(readJson(twPaddingPath))
    : [];
  const twMarginTokens = fs.existsSync(twMarginPath)
    ? collectLeafTokens(readJson(twMarginPath))
    : [];

  const header =
    "/* AUTO-GENERATED FILE. DO NOT EDIT.\n" +
    " * Generated by: node scripts/build-tokens.mjs\n" +
    " * Sources:\n" +
    " * - public/variables/mode/{light mode,dark mode}.tokens.json\n" +
    " * - public/variables/tokens/Mode 1.tokens.json\n" +
    " * - public/variables/tw_font/Mode 1.tokens.json\n" +
    " * - public/variables/tw_colors/Mode 1.tokens.json\n" +
    " */\n";

  const css =
    header +
    "\n" +
    // A universal “unit” to convert numeric tokens to lengths without inventing values.
    ":root {\n  --gs-px: 1px;\n}\n\n" +
    // Semantic colors + semantic foundations (from mode collection)
    renderBlock(":root", lightTokens, { prefix: "gs" }) +
    "\n\n" +
    // Numeric constants (source-of-truth scale)
    renderBlock(":root", numberTokens, { prefix: "gs-n" }) +
    "\n\n" +
    // Typography tokens (family/size/weight/etc.)
    renderBlock(":root", twFontTokens, { prefix: "gs-font" }) +
    "\n\n" +
    // Tailwind-like primitive palette (used when the frame specifies a non-semantic fill)
    renderBlock(":root", twColorTokens, { prefix: "gs-tw" }) +
    "\n\n" +
    // Spacing tokens (gap, space, padding, margin)
    renderBlock(":root", twGapTokens, { prefix: "gs-gap" }) +
    "\n\n" +
    renderBlock(":root", twSpaceTokens, { prefix: "gs-space" }) +
    "\n\n" +
    renderBlock(":root", twPaddingTokens, { prefix: "gs-padding" }) +
    "\n\n" +
    renderBlock(":root", twMarginTokens, { prefix: "gs-margin" }) +
    "\n\n" +
    renderBlock(".theme-dark", darkTokens, { prefix: "gs" }) +
    "\n";

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, css, "utf8");
  console.log(
    `Wrote ${path.relative(root, outFile)} (mode ${lightTokens.length}+${darkTokens.length}, n ${numberTokens.length}, font ${twFontTokens.length}, tw ${twColorTokens.length}, spacing ${twGapTokens.length + twSpaceTokens.length + twPaddingTokens.length + twMarginTokens.length})`,
  );
}

main();

